# -*- coding: utf-8 -*-
"""CNN_occlusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13gc90aMdftOnZguLSXcPVWR9tyRTAqx_
"""

import os
import tensorflow as tf
import numpy as np
import math
from PIL import Image, ImageOps
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout, MaxPool2D, LeakyReLU, Flatten, Dense, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.applications import xception
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow.keras.backend as kb

print(tf.__version__)

"""# Get the Data"""

cifar10 = tf.keras.datasets.cifar10

(X_train, y_train), (X_test, y_test) = cifar10.load_data()

# print(X_train.shape, y_train.shape)
x_shape = X_train[0].shape
print(x_shape)

y_train, y_test = y_train.flatten(), y_test.flatten()